-
  id: 1-1-1
  message: Gift card giveaway  🎁   winners have been 📢 / 👀 for new tasks on Friday, Mar 4th! 🗓
  start_at: 2022-02-28
  end_at: 2022-03-03
-
  id: 1-2-1
  message: New studies 🧠  are now available! Happy learning!🤓
  start_at: 2022-03-04
  end_at: 2022-03-10
-
  id: 1-2-2
  message: Keep a good thing going - complete available studies ☑️ by Monday, Mar 21st to enter a gift card 🎁  giveaway!
  start_at: 2022-03-11
  end_at: 2022-03-13
-
  id: 1-2-3
  message: New gift card 🎁 giveaways will be awarded on April 8th, and new tasks will be available on Monday, April 11th! 🗓
  start_at: 2022-03-24
  end_at: 2022-04-08
-
  id: 1-2-4
  message: Gift card giveaway winners 🎁  have been chosen! 👀 for new tasks on Monday, April 11th!
  start_at: 2022-04-08
  end_at: 2022-04-10
-
  id: 1-3-1
  message: A month of learning beckons - access our all new studies! 👓
  start_at: 2022-04-11
  end_at: 2022-04-21
-
  id: 1-3-2
  message: Lucky you - studies 📚 are still available to enter an exciting gift card giveaway!🎁
  start_at: 2022-04-22
  end_at: 2022-04-28
-
  id: 1-3-3
  message: Gift card giveaways 📢 on Friday, May 6th! 🥳
  start_at: 2022-04-29
  end_at: 2022-05-05
-
  id: 1-3-4
  message: Gift card 🎁 giveaway winners have been chosen! Continue exploring - the rewards 🏆 haven't ended yet!
  start_at: 2022-05-06
  end_at: 2022-05-08
-
  id: 1-3-5
  message: Last chance ⏳ to complete all studies by May 12 for a chance to win a pair of Apple AirPods! 🎧
  start_at: 2022-05-09
  end_at: 2022-05-12
