development:
  featured_studies: [ SV_dhQOqcMTVFaUkyq, SV_6DzlBZlWxmmsnUW ]
  syllabus_contest_studies: [ SV_dhQOqcMTVFaUkyq, SV_6DzlBZlWxmmsnUW ]
  export_cache_hours: 0
  chatbot:
    table_name: <%= ENV.fetch('CHATBOT_TABLE_NAME', 'production-research-chatbot-db') %>
  qualtrics_api_key: <%= ENV.fetch('QUALTRICS_API_KEY', '000000') %>
  qualtrics_api_url: https://iad1.qualtrics.com/API/v3
  qualtrics_group_library: 'GR_7R5NeLAPtj22K46'
  qualtrics_launch_url: <%= ENV.fetch('QUALTRICS_LAUNCH_URL', 'https://riceuniversity.co1.qualtrics.com/jfe/form') %>
  qualtrics_template_survey_id: <%= ENV.fetch('QUALTRICS_TEMPLATE_SURVEY_ID', 'SV_cA5YICrqMwDcNXU') %>
  qualtrics_template_survey_secret_key: <%= ENV.fetch('QUALTRICS_TEMPLATE_SURVEY_SECRET_KEY', 'NLygf4wBFh1xIpm0') %>
  demographic_survey_id: <%= ENV.fetch('DEMOGRAPHIC_SURVEY_ID', 'SV_6xGQzj4OBJnxGuy') %>
  enclave_api_key: ec_dev_1bG346BDBGEsG5Dck8H6sAiRBJ7Vt52Vwcno
  homepage_url: <%= ENV.fetch('HOMEPAGE_URL', 'http://localhost:4000') %>
  frontend_url: http://localhost:4000
  admin_uuids: <%= ENV.fetch('ADMIN_UUIDS', '00000000-0000-0000-0000-000000000000') %>
  secret_key_base: 517a4eb6769e6ce0399f4e345873ecd1d2d92b11e53b7ec0a281a6ceaa3762d627211d92d0de478198dad362417343993262c983c161004c47756ec1ff4511b8
  accounts:
    env_name: <%= ENV.fetch('ACCOUNTS_ENV_NAME', 'dev') %>
    oauth:
      url: 'https://dev.openstax.org/accounts/'
      client_id: <%= ENV['ACCOUNTS_OAUTH_CLIENT_ID'] %>
      secret: <%= ENV['ACCOUNTS_OAUTH_SECRET'] %>
    sso:
      cookie_name: 'oxa_dev'
      signature_public_key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxItufComL1S+j+U2JVr4
        aeIPyZYJR8S3RcxXjlHgybrAsBf/zyAjJlOBIhVfrm9jUF1HKNMyiTKQehG5XBBW
        /F8DQT5vGdBd4g9WIAmNU0E+symeF4X+mFIZ6dYwTMKtZxv1U0nkJ8xL2q4jCFVB
        UMlQRmz9EffSz+fmXr9xGQj80HKahzciM6m2aspX096qUP90155qmLEayE2uhs5C
        oAUbahA+VXS6ggsCUeVyog5Z1mC086d8r78ylr1y8IQ3aazdJE/mKxfqvu9S423h
        wNzBP6Fp0n68ZjUdUirqAZEbSrioJgFLEzX8ef7XilTL9dKLSS1w09ErctAF+Tor
        hwIDAQAB
        -----END PUBLIC KEY-----
      encryption_private_key: 'RvGHVZ/kvzUAA5Z3t68+FNhuMCJxkzv+'

test:
  export_cache_hours: 0
  chatbot:
    table_name: chatbot-test
  qualtrics_api_key: <%= ENV.fetch('QUALTRICS_API_KEY', '') %>
  qualtrics_api_url: https://iad1.qualtrics.com/API/v3
  qualtrics_group_library: 'GR_7R5NeLAPtj22K46'
  qualtrics_launch_url: <%= ENV.fetch('QUALTRICS_LAUNCH_URL', 'https://riceuniversity.co1.qualtrics.com/jfe/form') %>
  qualtrics_template_survey_id: <%= ENV.fetch('QUALTRICS_TEMPLATE_SURVEY_ID', 'SV_6xGQzj4OBJnxGuy') %>
  qualtrics_template_survey_secret_key: <%= ENV.fetch('QUALTRICS_TEMPLATE_SURVEY_SECRET_KEY', 'NLygf4wBFh1xIpm0') %>
  demographic_survey_id: <%= ENV.fetch('DEMOGRAPHIC_SURVEY_ID', 'SV_6xGQzj4OBJnxGuy') %>
  enclave_api_key: ec_test_26u7kYS6TgHg50dl4n8tzEMWekJAwi2fy5cH
  homepage_url: <%= ENV.fetch('HOMEPAGE_URL', 'http://localhost:4000') %>
  frontend_url: http://localhost:4000
  secret_key_base: 1b42c4386b75cda9a082a05fee60398c037b52ed0b6f059ff116c33b84f3ea3dfff036e79273e1e3dd59f325fd2ed179de2937b06778d38343591a2032b0b424
  accounts:
    env_name: <%= ENV.fetch('ACCOUNTS_ENV_NAME', 'dev') %>
    oauth:
      url: 'https://dev.openstax.org/accounts/'
      client_id: <%= ENV['ACCOUNTS_OAUTH_CLIENT_ID'] %>
      secret: <%= ENV['ACCOUNTS_OAUTH_SECRET'] %>
    sso:
      cookie_name: 'oxa_dev'
      signature_public_key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxItufComL1S+j+U2JVr4
        aeIPyZYJR8S3RcxXjlHgybrAsBf/zyAjJlOBIhVfrm9jUF1HKNMyiTKQehG5XBBW
        /F8DQT5vGdBd4g9WIAmNU0E+symeF4X+mFIZ6dYwTMKtZxv1U0nkJ8xL2q4jCFVB
        UMlQRmz9EffSz+fmXr9xGQj80HKahzciM6m2aspX096qUP90155qmLEayE2uhs5C
        oAUbahA+VXS6ggsCUeVyog5Z1mC086d8r78ylr1y8IQ3aazdJE/mKxfqvu9S423h
        wNzBP6Fp0n68ZjUdUirqAZEbSrioJgFLEzX8ef7XilTL9dKLSS1w09ErctAF+Tor
        hwIDAQAB
        -----END PUBLIC KEY-----
      encryption_private_key: 'RvGHVZ/kvzUAA5Z3t68+FNhuMCJxkzv+'

production:
  export_cache_hours: 6
  chatbot:
    table_name: <%= ENV.fetch('CHATBOT_TABLE_NAME', 'production-research-chatbot-db') %>
  qualtrics_api_key: <%= ENV.fetch('QUALTRICS_API_KEY', '') %>
  qualtrics_group_library: 'GR_7R5NeLAPtj22K46'
  qualtrics_api_url: https://iad1.qualtrics.com/API/v3
  qualtrics_launch_url: <%= ENV.fetch('QUALTRICS_LAUNCH_URL', 'https://riceuniversity.co1.qualtrics.com/jfe/form') %>
  qualtrics_template_survey_id: <%= ENV.fetch('QUALTRICS_TEMPLATE_SURVEY_ID', 'SV_6xGQzj4OBJnxGuy') %>
  qualtrics_template_survey_secret_key: <%= ENV.fetch('QUALTRICS_TEMPLATE_SURVEY_SECRET_KEY', 'NLygf4wBFh1xIpm0') %>
  demographic_survey_id: <%= ENV.fetch('DEMOGRAPHIC_SURVEY_ID', 'SV_6xGQzj4OBJnxGuy') %>
  featured_studies: <%= ENV.fetch('FEATURED_STUDY_IDS', 'SV_bkdwJwB4iOgcYXs').split(',') %>
  syllabus_contest_studies: <%= ENV.fetch('SYLLABUS_CONTEST_STUDIES', '').split(',') %>
  homepage_url: <%= ENV.fetch('HOMEPAGE_URL', 'https://openstax.org/kinetic/') %>
  frontend_url: ''
  enclave_api_key: <%= ENV['ENCLAVE_API_KEY'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  sentry:
    dsn: <%= ENV['SENTRY_DSN'] %>
  admin_uuids: <%= ENV['ADMIN_UUIDS'] %>
  accounts:
    env_name: <%= ENV.fetch('ACCOUNTS_ENV_NAME', 'staging') %>
    oauth:
      url: <%= ENV['ACCOUNTS_OAUTH_URL'] %>
      client_id: <%= ENV['ACCOUNTS_OAUTH_CLIENT_ID'] %>
      secret: <%= ENV['ACCOUNTS_OAUTH_SECRET'] %>
    sso:
      signature_public_key: |-
        <%= ENV.fetch('COOKIE_PUBLIC_KEY', '').indent(8) %>
      encryption_private_key: |-
        <%= ENV.fetch('COOKIE_PRIVATE_KEY', '').indent(8) %>
      cookie_name: <%= ENV.fetch('COOKIE_NAME', 'oxa') %>
