development:
  secret_key_base: 517a4eb6769e6ce0399f4e345873ecd1d2d92b11e53b7ec0a281a6ceaa3762d627211d92d0de478198dad362417343993262c983c161004c47756ec1ff4511b8
  host: <% 'localhost:8000' %>
  qualtrics_launch_url: <%= ENV.fetch('QUALTRICS_LAUNCH_URL', 'https://riceuniversity.co1.qualtrics.com/jfe/form') %>
  accounts:
    env_name: <%= ENV.fetch('ACCOUNTS_ENV_NAME', 'dev') %>
    sso:
      cookie_name: 'oxa_dev'
      signature_public_key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxItufComL1S+j+U2JVr4
        aeIPyZYJR8S3RcxXjlHgybrAsBf/zyAjJlOBIhVfrm9jUF1HKNMyiTKQehG5XBBW
        /F8DQT5vGdBd4g9WIAmNU0E+symeF4X+mFIZ6dYwTMKtZxv1U0nkJ8xL2q4jCFVB
        UMlQRmz9EffSz+fmXr9xGQj80HKahzciM6m2aspX096qUP90155qmLEayE2uhs5C
        oAUbahA+VXS6ggsCUeVyog5Z1mC086d8r78ylr1y8IQ3aazdJE/mKxfqvu9S423h
        wNzBP6Fp0n68ZjUdUirqAZEbSrioJgFLEzX8ef7XilTL9dKLSS1w09ErctAF+Tor
        hwIDAQAB
        -----END PUBLIC KEY-----
      encryption_private_key: 'RvGHVZ/kvzUAA5Z3t68+FNhuMCJxkzv+'
test:
  host: <% 'localhost:8000' %>
  secret_key_base: 1b42c4386b75cda9a082a05fee60398c037b52ed0b6f059ff116c33b84f3ea3dfff036e79273e1e3dd59f325fd2ed179de2937b06778d38343591a2032b0b424
  qualtrics_launch_url: <%= ENV.fetch('QUALTRICS_LAUNCH_URL', 'https://riceuniversity.co1.qualtrics.com/jfe/form') %>
  accounts:
    env_name: <%= ENV.fetch('ACCOUNTS_ENV_NAME', 'dev') %>
    sso:
      cookie_name: 'oxa_dev'
      signature_public_key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxItufComL1S+j+U2JVr4
        aeIPyZYJR8S3RcxXjlHgybrAsBf/zyAjJlOBIhVfrm9jUF1HKNMyiTKQehG5XBBW
        /F8DQT5vGdBd4g9WIAmNU0E+symeF4X+mFIZ6dYwTMKtZxv1U0nkJ8xL2q4jCFVB
        UMlQRmz9EffSz+fmXr9xGQj80HKahzciM6m2aspX096qUP90155qmLEayE2uhs5C
        oAUbahA+VXS6ggsCUeVyog5Z1mC086d8r78ylr1y8IQ3aazdJE/mKxfqvu9S423h
        wNzBP6Fp0n68ZjUdUirqAZEbSrioJgFLEzX8ef7XilTL9dKLSS1w09ErctAF+Tor
        hwIDAQAB
        -----END PUBLIC KEY-----
      encryption_private_key: 'RvGHVZ/kvzUAA5Z3t68+FNhuMCJxkzv+'

production:
  host: <% ( ENV['HEROKU_PR_NUMBER'] ?
           "pr-#{ENV['HEROKU_PR_NUMBER']}.kinetic.sandbox.openstax.org" : ENV.fetch('HOST', 'kinetic.openstax.org') ) %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  sentry:
    dsn: <%= ENV['SENTRY_RAILS_DSN'] %>
  admin_uuids: <%= ENV['ADMIN_UUIDS'] %>
  qualtrics_launch_url: <%= ENV.fetch('QUALTRICS_LAUNCH_URL', 'https://riceuniversity.co1.qualtrics.com/jfe/form') %>
  env_name: <%= ENV.fetch('ACCOUNTS_ENV_NAME', 'staging') %>
  accounts:
    sso:
      signature_public_key: |-
<%= ENV.fetch('COOKIE_PUBLIC_KEY', '').indent(8) %>

      encryption_private_key: |-
<%= ENV.fetch('COOKIE_PRIVATE_KEY', '').indent(8) %>

      cookie_name: <%= ENV.fetch('COOKIE_NAME', 'oxa') %>
