name: Lint

on: [ push, pull_request ]

jobs:
  ruby:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop
        with:
          working-directory: backend

  typescript:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@HEAD
        with:
          working-directory: frontend
      - name: Run lint
        working-directory: frontend
        run: yarn run lint
      - name: Run typecheck
        working-directory: frontend
        run: yarn run typecheck
