name: Lint

on: [ pull_request ]

jobs:
  ruby:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
          working-directory: backend

      - name: Run Rubocop
        working-directory: backend
        run: bundle exec rubocop

  typescript:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend
      - name: Run lint
        working-directory: frontend
        run: yarn run lint
      - name: Run typecheck
        working-directory: frontend
        run: yarn run typecheck
