name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rspec:
    timeout-minutes: 10
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build docker image and run specs within it
        run: |
          CI_ENV=`bash <(curl -s https://codecov.io/env)`
          docker-compose up --build -d
          docker-compose exec -T -e CI_ENV="$CI_ENV" api rspec
      - name: Stop containers
        if: always()
        run: docker-compose down
