name: Tests2

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rspec:
    timeout-minutes: 10
    runs-on: ubuntu-18.04
    # services:
    #   postgres:
    #     image: postgres:11
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_DB: labs_test
    #       POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build docker image and run specs within it
        # See https://docs.codecov.io/docs/testing-with-docker
        run: |
          docker-compose up --build -d
          docker-compose exec -T api rspec

      # docker-compose exec -e CI_ENV=`bash <(curl -s https://codecov.io/env)` api rspec
      # - name: Stop containers
      #     if: always()
      #     run: docker-compose -f down
